---
apiVersion: v1
kind: Namespace
metadata:
  name: microservices
---
apiVersion: v1
kind: Service
metadata:
  name: auction-house-primary
  namespace: microservices
spec:
  selector:
    app: auction-house-primary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auction-house-primary
  namespace: microservices
  annotations:
    kubernetes.io/ingress.class: "tectonic"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
      - auction-house-primary.local
  rules:
  - host: auction-house-primary.local
    http:
      paths:
      - backend:
          serviceName: auction-house-primary
          servicePort: 80
        path: /
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auction-house-primary
  namespace: microservices
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auction-house-primary
        monitoring-group: microservices-metrics
    spec:
      containers:
        - name: auction-house-primary
          image: docker-registry.local/auction-house-primary-async
          resources:
            limits:
              memory: "192Mi"
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: http_port
              value: "8080"
            - name: CASSANDRA_CONTACT_POINT
              value: "cassandra-0.cassandra.databases.svc.cluster.local"
            - name: BILLING_SERVICE_CONTACT_POINT
              value: "billing-service-secondary.microservices.svc.cluster.local"
            - name: IDENTITY_SERVICE_CONTACT_POINT
              value: "identity-service-tertiary.microservices.svc.cluster.local"