---
apiVersion: v1
kind: Namespace
metadata:
  name: microservices
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service-tertiary-async
  namespace: microservices
spec:
  selector:
    app: identity-service-tertiary-async
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: identity-service-tertiary-async
  namespace: microservices
  annotations:
    kubernetes.io/ingress.class: "tectonic"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
      - identity-service-tertiary-async.local
  rules:
  - host: identity-service-tertiary-async.local
    http:
      paths:
      - backend:
          serviceName: identity-service-tertiary-async
          servicePort: 443
        path: /
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identity-service-tertiary-async
  namespace: microservices
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-service-tertiary-async
        monitoring-group: microservices-metrics
    spec:
      containers:
        - name: identity-service-tertiary-async
          image: docker-registry.local/identity-service-tertiary-async
          resources:
            limits:
              memory: "192Mi"
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: http_port
              value: "8080"
            - name: CASSANDRA_CONTACT_POINT
              value: "cassandra-0.cassandra.databases.svc.cluster.local"
