apiVersion: batch/v1
kind: Job
metadata:
  name: run-load-tests-sync
  namespace: microservices
spec:
  selector: {}
  template:
    metadata:
      name: run-load-tests-sync
    spec:
      containers:
      - name: gatling
        image: docker-registry.local/gatling-tests:latest
        imagePullPolicy: Always
        # if using S3 remember to add env vars:
        # > AWS_ACCESS_KEY_ID
        # > AWS_SECRET_ACCESS_KEY
        env:
          - name: TEST_SUBJECT_HOST
            value: "auction-house-primary-sync.microservices.svc.cluster.local"
          - name: TEST_SUBJECT_PORT
            value: "80"
          - name: GATLING_USE_S3
            value: "false"
      restartPolicy: Never
